"""
Research Automation Script
Creator: Md Jamil Islam
Purpose: Automate research report generation for marketing agencies
"""

import json
import os
from datetime import datetime


REPORT_TEMPLATE = """
# Research Report: {company_name}

**Prepared by:** Md Jamil Islam
**Date:** {date}
**Client:** {client_name}

---

## Executive Summary

{summary}

---

## Industry Analysis

### Market Size
{market_size}

### Key Trends
{trends}

### Competitor Overview
{competitors}

---

## Recommendations

{recommendations}

---

## Next Steps

{next_steps}

---
*Report generated by Agency Research Automation*
*Creator: Md Jamil Islam*
"""


def generate_report(
    company_name: str,
    client_name: str,
    niche: str = "digital marketing",
) -> str:
    """Generate a research report for a given company."""
    today = datetime.today().strftime("%B %d, %Y")

    summary = (
        f"This report provides a comprehensive analysis of {company_name}'s "
        f"market position in the {niche} space. Key opportunities for growth "
        f"and competitive differentiation have been identified."
    )

    market_size = (
        f"The {niche} industry is valued at $500B+ globally with 15% YoY growth. "
        f"{company_name}'s target segment represents approximately $50B in addressable market."
    )

    trends = "\n".join(
        [
            f"- AI-powered {niche} tools adoption up 45% YoY",
            "- Short-form video content driving 3x more engagement",
            "- Data-driven personalization becoming standard expectation",
            "- Voice search optimization growing rapidly",
            "- Sustainability messaging resonating strongly with Gen Z/Millennial buyers",
        ]
    )

    competitors = "\n".join(
        [
            f"| Competitor | Strength | Weakness |",
            f"|-----------|---------|---------|",
            f"| Competitor A | Strong brand | High pricing |",
            f"| Competitor B | Wide reach | Slow delivery |",
            f"| Competitor C | Low cost | Poor quality |",
        ]
    )

    recommendations = "\n".join(
        [
            f"1. Focus on {niche} automation to reduce costs by 30%",
            "2. Develop a content flywheel to scale organic reach",
            "3. Implement data-driven client reporting dashboards",
            "4. Offer performance-based pricing to attract risk-averse clients",
        ]
    )

    next_steps = "\n".join(
        [
            "- Schedule strategy call within 48 hours",
            "- Deliver full competitive audit in 5 business days",
            "- Set up weekly reporting dashboard",
            "- Review KPIs at 30-day mark",
        ]
    )

    return REPORT_TEMPLATE.format(
        company_name=company_name,
        date=today,
        client_name=client_name,
        summary=summary,
        market_size=market_size,
        trends=trends,
        competitors=competitors,
        recommendations=recommendations,
        next_steps=next_steps,
    )


def save_report(report: str, filename: str) -> None:
    """Save a report to a markdown file."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Report saved to {filename}")


def main():
    print("=== Research Automation Script ===")
    print(f"Creator: Md Jamil Islam")
    print(f"Date: {datetime.today().strftime('%Y-%m-%d')}")
    print()

    # Example: generate 3 sample reports
    samples = [
        {"company": "TechBoost Agency", "client": "Client A", "niche": "SaaS marketing"},
        {"company": "GrowthLab", "client": "Client B", "niche": "e-commerce marketing"},
        {"company": "ContentForge", "client": "Client C", "niche": "content marketing"},
    ]

    for idx, sample in enumerate(samples, 1):
        print(f"Generating report {idx}/{len(samples)}: {sample['company']}...")
        report = generate_report(
            company_name=sample["company"],
            client_name=sample["client"],
            niche=sample["niche"],
        )
        filename = f"templates/sample_report_{idx}.md"
        save_report(report, filename)

    print("\nAll sample reports generated successfully!")
    print("Find them in the templates/ directory.")


if __name__ == "__main__":
    main()
